### ISSUE TITLE
[BUG] unable to download "Forbidden Your login session might be expired"

### ISSUE THREAD

**Issue by MinamikoAAAA** [EltonChou/TwitterMediaHarvest#149] opened 2024-05-17 00:11 UTC
After the 4.2.5 update, the download button shows up again. However, the extension is still unable to download any media.
The console warning is shown below:
![error](https://github.com/EltonChou/TwitterMediaHarvest/assets/79541268/4b632650-52ca-4c0d-a377-1414cb926b1c)
Log file:
[x.com-1715903685086.log](https://github.com/EltonChou/TwitterMediaHarvest/files/15342171/x.com-1715903685086.log)
Occasionally, a pop-up window will show the below message:
![error2](https://github.com/EltonChou/TwitterMediaHarvest/assets/79541268/caf8c120-176c-4239-a336-dd3e96b5d31a)
Clicking the "View" button will copy the current tab, and the download button remains broken.

Chrome 125.0.6422.61, I'm living in New Zealand

**Comment by EltonChou** [comment] 2024-05-17 07:09
Can you go to options page's console to check `Network` and `Console` tab ?
I think they may deprecate some api endpoints.

**Comment by brgm0** [comment] 2024-05-17 12:21
The same symptoms occur on mac Chrome. Cannot download. . .

**Comment by MinamikoAAAA** [comment] 2024-05-18 15:06
> Can you go to options page's console to check `Network` and `Console` tab ? I think they may deprecate some api endpoints.
> 
> Remember to mask the sensitive data.

I don't understand your instructions completely... Could you specify the "option page" for me?

**Comment by EltonChou** [comment] 2024-05-18 15:26
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/12560310/8e1ce24d-7ecc-4a46-b23f-e49a2fff9072)

> I don't understand your instructions completely... Could you specify the "option page" for me?

**Comment by MinamikoAAAA** [comment] 2024-05-18 22:13
v4.2.6 works now. Thank you very much!

**Comment by globalgoldgetter** [comment] 2024-05-19 08:28
> I think I have found the root cause. So you don't need to do this.
> 
> FYI ![image](https://private-user-images.githubusercontent.com/12560310/331811787-8e1ce24d-7ecc-4a46-b23f-e49a2fff9072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDcxNjAsIm5iZiI6MTcxNjEwNjg2MCwicGF0aCI6Ii8xMjU2MDMxMC8zMzE4MTE3ODctOGUxY2UyNGQtN2VjYy00YTQ2LWIyM2YtZTQ5YTJmZmY5MDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA4MjEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjZhNDNhMmJlNzQ2YjIzYmVjNGNkNDY3ZDBjMTBiYTRkNWYyZjQxNmNmZmFmN2RlY2M1MzBjMjJjYjQ5NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CBhYIs9D0UCDEihoGbJ-YtiN2c0uXJI1mVI0hBP1J1s)
> 
> > I don't understand your instructions completely... Could you specify the "option page" for me?

Hi, I'm still unclear about what are we to do once checking the settings.  I dont see any "Network and Console tab."
Also, you mentioned: " I think I have found the root cause. So you don't need to do this."
What is the fix to download files again?

Thanks!

![Screen Shot 2024-05-19 at 1 09 12 AM](https://github.com/EltonChou/TwitterMediaHarvest/assets/170230502/9dc3d15b-bb0d-4d44-a901-8921203d80a5)

**Comment by MinamikoAAAA** [comment] 2024-05-19 08:32
> > I think I have found the root cause. So you don't need to do this.
> > FYI ![image](https://private-user-images.githubusercontent.com/12560310/331811787-8e1ce24d-7ecc-4a46-b23f-e49a2fff9072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDcxNjAsIm5iZiI6MTcxNjEwNjg2MCwicGF0aCI6Ii8xMjU2MDMxMC8zMzE4MTE3ODctOGUxY2UyNGQtN2VjYy00YTQ2LWIyM2YtZTQ5YTJmZmY5MDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA4MjEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjZhNDNhMmJlNzQ2YjIzYmVjNGNkNDY3ZDBjMTBiYTRkNWYyZjQxNmNmZmFmN2RlY2M1MzBjMjJjYjQ5NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CBhYIs9D0UCDEihoGbJ-YtiN2c0uXJI1mVI0hBP1J1s)
> > > I don't understand your instructions completely... Could you specify the "option page" for me?
> 
> Hi, I'm still unclear about what are we to do once checking the settings. I dont see any "Network and Console tab." Also, you mentioned: " I think I have found the root cause. So you don't need to do this." What is the fix to download files again?
> 
> Thanks!
> 
> ![Screen Shot 2024-05-19 at 1 09 12 AM](https://private-user-images.githubusercontent.com/170230502/331857869-9dc3d15b-bb0d-4d44-a901-8921203d80a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDc2MDMsIm5iZiI6MTcxNjEwNzMwMywicGF0aCI6Ii8xNzAyMzA1MDIvMzMxODU3ODY5LTlkYzNkMTViLWJiMGQtNGQ0NC1hOTAxLTg5MjEyMDNkODBhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwODI4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2I4YTg0ZDU4MjkxOGYxZDc0NjNjNTVhZDE4NGJlMWZmOTljNWZmNWM4OGU1Zjk5ZTZiY2U5OWNiNDNjMmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jRwqLsbYCY0iAN8ryi5YkyGSe7zp1tAxxqZ83E4U7VY)

the V4.2.6 update is available in the "Releases" session. Go download it and check if it solves the issue.

**Comment by globalgoldgetter** [comment] 2024-05-19 15:31
Working perfectly after downloading the update. 
Is there an option to download the title of the file posted?

Thanks!

**Comment by EltonChou** [comment] 2024-05-19 16:16
> Working perfectly after downloading the update. Is there an option to download the title of the file posted?
> 
> Thanks!

If you can defined what is a meaningful `title` in all situations.

**Comment by globalgoldgetter** [comment] 2024-05-19 16:48
> > Working perfectly after downloading the update. Is there an option to download the title of the file posted?
> > Thanks!
> 
> If you can defined what is a meaningful `title` in all situations.

Yes, for instance see the attached images. The area I have circled.
![Screen Shot 2024-05-19 at 9 44 10 AM](https://github.com/EltonChou/TwitterMediaHarvest/assets/170230502/f9d9661d-1a22-4f3f-a8bd-d23f9c74bbc4)
![Screen Shot 2024-05-19 at 9 46 31 AM](https://github.com/EltonChou/TwitterMediaHarvest/assets/170230502/fc37b65d-6fcc-4526-82b5-2c7406dcb23d)

**Comment by globalgoldgetter** [comment] 2024-05-19 17:41
Doh! I forhet you devleopers speak differently . You meant something else when you replied "If you can defined what is a meaningful title in all situations." Meaning what? How would one define "what is a meaningful title in all situations?" And where?

**Comment by EltonChou** [comment] 2024-05-19 18:31
If you want the *title* to be in filename, you will need to solve these problems.

1. Not all characters can be used in filename.
2. If the character is invalid in filename, how do you process it? Remove or swap?
3. Tweet's content length could be up to 4000 characters. Is it possible to be included in filename?

Another possible solution is storing the content in Indexed DB like history data.
When you need it, just search it. But the performance would not be good.
If you want to improve performance, I will need to host a service to serve those data and it will not be a **free feature**.

**Comment by moxin3** [comment] 2024-05-20 17:53
> v4.2.6 works now. Thank you very much!

iam new how to build this one to use it in chrome pls help

**Comment by 0x2E16CF0F** [comment] 2024-05-21 09:23
On the most recent release for Firefox, the same problem occurs when using Multi-Account Containers.
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/151734472/5097cc1d-753b-45a3-b804-137b17abfd91)

There is no error or warning logged by the Dev Tools when this happens, as I think that the issue happens outside of the container Twitter is running in.

For example, https://github.com/Flkalas/TwitterMediaAssist 's extension does work with Multi-Account Containers.

**Comment by EltonChou** [comment] 2024-05-21 11:06
> On the most recent release for Firefox, the same problem occurs when using Multi-Account Containers.
> There is no error or warning logged by the Dev Tools when this happens, as I think that the issue happens outside of the container Twitter is running in.
> 
> For example, https://github.com/Flkalas/TwitterMediaAssist 's extension does work with Multi-Account Containers.

https://github.com/EltonChou/TwitterMediaHarvest/issues/99#issuecomment-1713755005

**Comment by EltonChou** [comment] 2024-05-29 12:57
Should be fixed in `v4.2.6`

**Closed by EltonChou** 2024-05-29 12:57 UTC
Labels: bug
