### ISSUE TITLE
[BUG] Browser freezing on start up

### ISSUE THREAD

**Issue by Marthorya** [EltonChou/TwitterMediaHarvest#133] opened 2023-12-30 12:30 UTC
Brower - Opera GX version  LVL5 (core: 105.0.4970.63)

Extension worked flawlessly on first few days i got it and used it,
Then few days later the freezing on startup begun.

When i launch the browser it freezes for a moment .sometimes up to minute/s
after browser unfreezes there are no further issues.
after i disabled the TwitterMediaHarvest extension the browser launched normally.

I tried to erase  folder of all downloads and start browser with extension enabled ,it didn't seem to have any effect.

at the moment size of the  TwitterMediaHarvest downloads folder is 46.3 Mb
it includes media from 19 different creators.

**Comment by EltonChou** [comment] 2023-12-30 12:37
How many twitter tabs you opened when launch the browser?

**Comment by Marthorya** [comment] 2023-12-30 12:47
None.

**Comment by EltonChou** [comment] 2023-12-30 14:03
Can't reproduce this issue.
Maybe you can try another browser to check if the same problem happens again.

**Comment by Marthorya** [comment] 2023-12-30 14:18
Ill try it on chrome and see if same thing starts happening in few days

**Comment by EltonChou** [comment] 2023-12-30 14:23
Before you remove the extension, please note the id in options page ( options > About ).
Somthing like this image.
![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/12560310/e3311d55-fb58-4649-beee-52dc26ffa47f)

**Comment by Marthorya** [comment] 2024-01-03 20:02
Alright so. so far no issues on Chrome ,  my only guess it might be some sortof conflict with other extension 

for what it woroth, extnesion i have on Opera GX are :

* Adblock Plus - free ad blocker
* BlockTube
* Install Chrome Extensions
* ZED: Zoom Easy Downloader
* Unhook - Remove YouTube Recommended Videos
* Save image as Type
* Save Image As PNG
* Return YouTube Dislike
* Opera Ad Blocker


i mentioned this just incase someone else has this issue with Opera GX in future and might have more info.

**Comment by EltonChou** [comment] 2024-01-08 12:39
Since this issue was not a general problem or might caused by other extension, I will close it.
Feel free to reopen if you found the root cause.

**Closed by EltonChou** 2024-01-08 12:39 UTC
Labels: bug
