### ISSUE TITLE
[BUG]When a video has a link, it automatically opens the link in a new tab.

### ISSUE THREAD

**Issue by kidzgy** [EltonChou/TwitterMediaHarvest#83] opened 2023-07-12 07:04 UTC
**Describe the bug**
Whether on the homepage or in a specific tweet, if the tweet is viewed and the tweet is a video and the video contains a link, the link will automatically be opened in a new tab.
If the extension is turned off, there is no such problem.

**To Reproduce**
https://twitter.com/caijinglengyan/status/1679001055647137792

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows10 x64
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 115

**Comment by EltonChou** [comment] 2023-07-12 08:59
Thanks for the report.
This bug was caused by auto revealing feature, it would be fixed in next patch.

**Closed** 2023-07-12 09:52 UTC
Labels: bug
