### ISSUE TITLE
[BUG] Extension Crashes Brave Broswer

### ISSUE THREAD

**Issue by JFDW01** [EltonChou/TwitterMediaHarvest#193] opened 2024-09-20 02:09 UTC
Since earlier today whenever I click the download button it crashes Brave Browser. The file appears to download but then just shuts the browser down.

Going to the Downloads folder there's a .TMP file but no image file. I've tried downloading manually through other websites and they are working normally. This suggests it's isolated to this extension and that it is trying to download but is having an issue for some reason.

I've tried clearing the folder and deleting TMP files. Tweaking settings in the browser (ask location, removing Brave shields, etc) doesn't appear to change anything. Same goes for changing settings in the extension.

I've tried getting rid of extensions that may be interfering. Also tried this same extension on Google Chrome but over there it works normally. Even tried rebooting the computer (as the browser was behaving oddly for a little while).

I've tried uninstalling Brave and installing clean and the same issue happens.

If you can try this same thing in Brave and see if the same issue comes up. Go to a tweet, click the download button, and see if the issue repeats for you with the browser crashing and closing.

**Desktop (please complete the following information):**
 - Windows 10 Home Ver 22H2 OS Build 9045.4894
 - Brave Version 1.70.117 Chromium: 129.0.6668.59 (Official Build) (64-bit)

**Comment by EltonChou** [comment] 2024-09-20 13:38
I think they might break something in the latest version.
If the extension can work properly in older version then it should work in latest version when there is no breaking change on web extension api.

I will take a look if there might be some potential bugs.

**Comment by EltonChou** [comment] 2024-09-21 18:57
Related issue.

https://community.brave.com/t/brave-release-1-70-117-causing-problems-with-access-to-many-sites/570098
https://community.brave.com/t/braves-issues-today/569998

**Comment by EltonChou** [comment] 2024-09-22 11:37
This issue was caused by brave. It crash when extension calls `chrome.downloads.download()`.
I can do nothing on this.

https://github.com/brave/brave-browser/issues/41179

**Comment by JFDW01** [comment] 2024-09-23 02:39
Sounds good. I'll look more into it on my end to see if any solution comes up. I wonder if it may be a good idea to note on the extension page that issues with Brave can occur until a resolution is found.

**Comment by EltonChou** [comment] 2024-09-23 09:57
> Sounds good. I'll look more into it on my end to see if any solution comes up. I wonder if it may be a good idea to note on the extension page that issues with Brave can occur until a resolution is found.

This is best practice.
But every edit on store needs to get reviewed and it take some times (1~7 days).
Once you send the request you can't update extension in this period.
If you really need to fix something, you have to cancel the request and it take times too.

**Comment by JFDW01** [comment] 2024-09-24 02:59
Sounds good. I will keep looking for resolutions with Brave and update with findings as they come.

Thank you for your help.

**Comment by iefremov** [comment] 2024-09-24 16:17
Fixed in https://github.com/brave/brave-browser/issues/41179

**Comment by EltonChou** [comment] 2024-09-24 20:08
@iefremov Thanks for your fix!

**Closed** 2024-09-24 20:07 UTC
Labels: chromium, browser-behavior

**Comment by JFDW01** [comment] 2024-09-24 22:45
Confirmed. Extension is working properly with the fix in above link. Also thank you @iefremov for the fix and @EltonChou for your help.
